backend:
  name: github
  repo: etcenterprise/ets-website
  branch: main

local_backend: false

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:

  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true

    fields:
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Client", name: "client", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}

  - name: "services"
    label: "Services"
    folder: "_services"
    create: true

    fields:
      - {label: "Service Name", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
